[Bulk] validation-Odata-docs-invalidAuthor2
MicrosoftDocs/OData-docs pull request #222
Opened 2022-04-21 21:56 UTC by Roudabeh1348

This PR fixes 16 issues across multiple categories in Odata-docs repo.

2022-04-21 21:57 UTC, opbld32 commented
Docs Build status updates of commit _[62d0d7d](https://github.com/Roudabeh1348/OData-docs/commits/62d0d7da3020c1f998fd4fc44d3c90ff72e91781)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) | [Details](#user-content-72fa4e418f7c9c65fdadb297bcf593c4-7423675d)
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) | [Details](#user-content-11b3300c388ec79f1a7962015483718e-7423675d)
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) | [Details](#user-content-dc13961d632952456806aa5d2bda0258-7423675d)
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) | [Details](#user-content-30e3fb08d3635b1ab7b192f4ce87b1c8-7423675d)
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) | [Details](#user-content-130cd9fb22f225efcea5edf9080dcc74-7423675d)
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) | [Details](#user-content-f69803d2438ffc751dbe6c24efa732a6-7423675d)
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) | [Details](#user-content-436aecd9942d5991ab48945fafe135e4-7423675d)
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) | [Details](#user-content-ee4a106670f859d19c7e0519e54680b1-7423675d)
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |

<a id="72fa4e418f7c9c65fdadb297bcf593c4-7423675d"></a>
### [Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="11b3300c388ec79f1a7962015483718e-7423675d"></a>
### [Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="dc13961d632952456806aa5d2bda0258-7423675d"></a>
### [Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Parse OData uri using OData Core APIs' is duplicated in 'odatalib/v6/use-uri-parser-v6.md(3,14)', 'odatalib/v7/use-uri-parser.md(3,14)'.`````

<a id="30e3fb08d3635b1ab7b192f4ce87b1c8-7423675d"></a>
### [Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Write OData payload using OData Core APIs' is duplicated in 'odatalib/v6/write-payload-v6.md(3,14)', 'odatalib/v7/write-payload.md(3,14)'.`````

<a id="130cd9fb22f225efcea5edf9080dcc74-7423675d"></a>
### [Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f69803d2438ffc751dbe6c24efa732a6-7423675d"></a>
### [Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="436aecd9942d5991ab48945fafe135e4-7423675d"></a>
### [Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create spatial instances' is duplicated in 'odatalib/v6/create-spatial-instances.md(3,14)', 'spatial/create-instances.md(3,14)'.`````

<a id="ee4a106670f859d19c7e0519e54680b1-7423675d"></a>
### [Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Define spatial properties in entity data models' is duplicated in 'odatalib/v6/define-spatial-property.md(3,14)', 'spatial/define-property.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204212156475987-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T21%3A57%3A44Z&sr=b&sp=r&sig=gUm4EijhfM7uw10zuQF8iBKs%2BL96ttKNIgL2%2BvCsQJ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

F [...]

2022-04-21 22:18 UTC, opbld32 commented
Docs Build status updates of commit _[38ae0dd](https://github.com/Roudabeh1348/OData-docs/commits/38ae0ddeca12271f83009b947393f991398d3c39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) |
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) |
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) |
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204212217430950-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T22%3A18%3A35Z&sr=b&sp=r&sig=hHIvGYniwTtaQjuBmCiSg0wYeCgFLyMhJpoqlYduWZ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 22:29 UTC, Roudabeh1348 commented
@xuzhg @odero @Michael Pizzo The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. 
This will eliminate potential accessibility, security, and usability issues. 
This PR includes only build validation fixes and does not change other content. 
Please review within five business days and merge or comment in the PR with any changes you’d like to see. 
Thank you!

2022-04-22 06:47 UTC, KenitoInc requested changes

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/odatalib/v7/type-annotation.md
> +description: "In ODataAnnotatable, there is a property called TypeAnnotation whose type is ODataTypeAnnotation. It is used to store the @odata.type annotation read from or written to the payload. "
```suggestion
description: "This section describes how to override type annotation during serialization"
```

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/odatalib/v7/use-uri-parser.md
> +description: "This post guides you through the URI parser for OData V4, which is released with ODataLib V6.0 and later."
```suggestion
description: "This section describes how to parse OData uri using the ODataUriParser."
```

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/overview.md
> +author: madansr7
Also include `ms.author`

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/resources/roadmap.md
> +description: "OData Version 4.01 adds various new features and removes a few restrictions. New OData 4.01 query features and simplified syntax can be supported as compatible extensions to OData 4.0 s
```suggestion
description: "This section describes the OData roadmap."
```

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/spatial/create-instances.md
> +description: "Create spatial instances using Spatial APIs."
```suggestion
description: "This section describes how to create spatial instances using Spatial APIs."
```

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/spatial/define-property.md
> +description: "Define spatial properties in entity data models using EdmLib APIs."
```suggestion
description: "This section describes how to define spatial properties in entity data models using EdmLib APIs."
```

2022-04-22 06:47 UTC, KenitoInc commented on Odata-docs/odatalib/v7/write-payload.md
> +description: "Write OData payloads including including service document, model metadata, entity set, entity, entity references, complex values, primitive values using OData Core APIs."
```suggestion
description: "This section describes how to write OData payloads including service document, model metadata, entity set, entity, entity references, complex values, primitive values using OData Core APIs."
```

2022-04-22 16:46 UTC, Roudabeh1348 commented on Odata-docs/odatalib/v7/type-annotation.md
> +description: "In ODataAnnotatable, there is a property called TypeAnnotation whose type is ODataTypeAnnotation. It is used to store the @odata.type annotation read from or written to the payload. "
fixed.

2022-04-22 16:48 UTC, Roudabeh1348 commented on Odata-docs/odatalib/v7/use-uri-parser.md
> +description: "This post guides you through the URI parser for OData V4, which is released with ODataLib V6.0 and later."
fixed.

2022-04-22 16:50 UTC, Roudabeh1348 commented on Odata-docs/overview.md
> +author: madansr7
fixed.

2022-04-22 16:51 UTC, Roudabeh1348 commented on Odata-docs/resources/roadmap.md
> +description: "OData Version 4.01 adds various new features and removes a few restrictions. New OData 4.01 query features and simplified syntax can be supported as compatible extensions to OData 4.0 s
fixed.

2022-04-22 16:52 UTC, Roudabeh1348 commented on Odata-docs/spatial/create-instances.md
> +description: "Create spatial instances using Spatial APIs."
fixed.

2022-04-22 16:53 UTC, Roudabeh1348 commented on Odata-docs/spatial/define-property.md
> +description: "Define spatial properties in entity data models using EdmLib APIs."
fixed.

2022-04-22 16:56 UTC, opbld31 commented
Docs Build status updates of commit _[edf1958](https://github.com/Roudabeh1348/OData-docs/commits/edf1958f0cb0f1903c9cbe9075189c4cdedc4ec6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) |
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) |
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) |
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204221656073609-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A56%3A47Z&sr=b&sp=r&sig=F7A9%2FKj9gNmIbs2P%2BemZF4ojmLGWtuik%2BSdHx%2B6bSY8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:58 UTC, Roudabeh1348 commented
@habbes @KenitoInc the suggested revisions for descriptions were made to the mentioned articles in this PR.

2022-04-25 11:06 UTC, KenitoInc approved these changes
LGTM

2022-04-26 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[4c3575c](https://github.com/Roudabeh1348/OData-docs/commits/4c3575c2d1f5e73ab620f976e5c6e2a48748681b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/fluent-writer-api.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/fluent-writer-api.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/fluent-writer-api?branch=pr-en-us-222) | [Details](#user-content-4506d7e47fbf7e25763d219b700ec897-dd298d9c)
[Odata-docs/odatalib/v7/json-batch.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/json-batch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/json-batch?branch=pr-en-us-222) | [Details](#user-content-11850b8b520efb13375ce659b5780305-dd298d9c)
[Odata-docs/odatalib/v7/navigation-partner.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/navigation-partner.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/navigation-partner?branch=pr-en-us-222) | [Details](#user-content-2565f5415e204a3b4dff4a37fe7c406c-dd298d9c)
[Odata-docs/odatalib/v7/nextpage-link-and-count-for-collection.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/nextpage-link-and-count-for-collection.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/nextpage-link-and-count-for-collection?branch=pr-en-us-222) | [Details](#user-content-2b2dd87a7484ad2c86fea2eca514f380-dd298d9c)
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) |
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) |
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) |
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) |

<a id="4506d7e47fbf7e25763d219b700ec897-dd298d9c"></a>
### [Odata-docs/odatalib/v7/fluent-writer-api.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/fluent-writer-api.md)
 - **Line 5, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'madansr7' is not a valid Microsoft alias.`````

<a id="11850b8b520efb13375ce659b5780305-dd298d9c"></a>
### [Odata-docs/odatalib/v7/json-batch.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/json-batch.md)
 - **Line 5, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'madansr7' is not a valid Microsoft alias.`````

<a id="2565f5415e204a3b4dff4a37fe7c406c-dd298d9c"></a>
### [Odata-docs/odatalib/v7/navigation-partner.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/navigation-partner.md)
 - **Line 5, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'madansr7' is not a valid Microsoft alias.`````

<a id="2b2dd87a7484ad2c86fea2eca514f380-dd298d9c"></a>
### [Odata-docs/odatalib/v7/nextpage-link-and-count-for-collection.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/nextpage-link-and-count-for-collection.md)
 - **Line 5, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'madansr7' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204261835097550-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T18%3A53%3A08Z&sr=b&sp=r&sig=LKWuGjazo1pKugjpzsnuvi5%2BVp9N1y7QgKO3t9wV9HY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[7b54fdf](https://github.com/Roudabeh1348/OData-docs/commits/7b54fdfa851ecf8842d4da4e1c79b2026e116184)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/fluent-writer-api.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/fluent-writer-api.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/fluent-writer-api?branch=pr-en-us-222) | [Details](#user-content-4506d7e47fbf7e25763d219b700ec897-7efe4682)
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) |
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) |
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) |
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) |

<a id="4506d7e47fbf7e25763d219b700ec897-7efe4682"></a>
### [Odata-docs/odatalib/v7/fluent-writer-api.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/fluent-writer-api.md)
 - **Line 5, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'madansr7' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204261840537593-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T18%3A55%3A49Z&sr=b&sp=r&sig=vhlvJwoHWsKBzgzdNfRYlXwNoqZuuYIXywo41c6IQsc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 19:56 UTC, Roudabeh1348 commented on Odata-docs/odatalib/v7/write-payload.md
> +description: "Write OData payloads including including service document, model metadata, entity set, entity, entity references, complex values, primitive values using OData Core APIs."
fixed.

2022-04-26 20:00 UTC, opbld30 commented
Docs Build status updates of commit _[4c43333](https://github.com/Roudabeh1348/OData-docs/commits/4c433339bfdfdd1e67c9f8de3dab3a532e897d59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Odata-docs/odatalib/v7/fluent-writer-api.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/fluent-writer-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/fluent-writer-api?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/support-untyped-json.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/support-untyped-json.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/support-untyped-json?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/type-annotation.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/type-annotation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/type-annotation?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/uri-parser-path-extensibility.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/uri-parser-path-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/uri-parser-path-extensibility?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/use-uri-parser.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/use-uri-parser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/use-uri-parser?branch=pr-en-us-222) |
[Odata-docs/odatalib/v7/write-payload.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/odatalib/v7/write-payload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/odatalib/write-payload?branch=pr-en-us-222) |
[Odata-docs/overview.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/overview?branch=pr-en-us-222) |
[Odata-docs/resources/roadmap.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/roadmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/roadmap?branch=pr-en-us-222) |
[Odata-docs/resources/support.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/resources/support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/resources/support?branch=pr-en-us-222) |
[Odata-docs/spatial/create-instances.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/create-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/create-instances?branch=pr-en-us-222) |
[Odata-docs/spatial/define-property.md](https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/spatial/define-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/odata/spatial/define-property?branch=pr-en-us-222) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef%5CPullRequest%5C202204261958563235-222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T20%3A00%3A49Z&sr=b&sp=r&sig=sdDFutfPr7aPQMPRpqL3c6Fje6Z5NcklsEgJxPHagVg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/2ea817ce-bd30-41f2-f2eb-9eb93b4d61ef?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 18:42 UTC, xuzhg approved these changes

2022-04-27 18:42 UTC, merged